### ISSUE TITLE
Somehting wrong

### ISSUE THREAD

**Issue by DyroS3** [esx-framework/esx_society#1]
Core Versions：v1.8.5
Society Versions：v1.8.5 + v1.9.0

Just happend for ambulance job,when I set my job grade to boss,I can't update for society money update frome hud
![image](https://user-images.githubusercontent.com/64310374/213910847-27dbfab0-ce36-4093-a9c9-bca7501d88c8.png)
other job work fine

**Comment by Flambaa** [comment]
Update core version and see how u go

**Comment by Gellipapa** [comment]
@DyroS3 Hi! Please update es_extended latest and recreate db tables. I think problem is sql tables.
